export const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL;
export const NEXT_PUBLIC_API_URL_BANNERS = process.env.NEXT_PUBLIC_API_URL_BANNERS;
export const NEXT_PUBLIC_VENDOR_TEMPLATE_URL = process.env.NEXT_PUBLIC_VENDOR_TEMPLATE_URL;
